image:
  file: .gitpod.Dockerfile

# Command to start on workspace startup (optional)
tasks:
  - init: yarn -cwd work/rescript install
    command: yarn -cwd work/rescript build

# Ports to expose on workspace startup (optional)
ports:
  - port: 8000
    onOpen: open-preview
